[config]
model = "bedrock/amazon.nova-pro-v1:0"

[github_action_config]
auto_review = true
auto_improve = true

[pr_reviewer]
extra_instructions = "answer in Japanese"
num_code_suggestions=3
inline_code_comments = true
ask_and_reflect = true

[pr_description]
extra_instructions = "answer in Japanese"

[pr_code_suggestions]
extra_instructions = "answer in Japanese"

[pr_add_docs]
extra_instructions = "answer in Japanese"

[pr_questions]
extra_instructions = "answer in Japanese"

[pr_update_changelog]
extra_instructions = "answer in Japanese"

[pr_test]
extra_instructions = "answer in Japanese"

[pr_improve_component]
extra_instructions = "answer in Japanese"
