language: php

php:
    - 7.2

services:
    - postgresql

before_script:
    - cp .env.travis .env
    - psql -c 'create database travis_ci_test;' -U postgres
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate
    - php artisan migrate

script:
    - phpunit
