version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: "${APP_DOMAIN} -> http://web:8000"
      STAGE: ${APP_ENV}
    volumes:
      - https-portal-data:/var/lib/https-portal
  web:
    image: nginx:1.17.8-alpine
    restart: always
    expose:
      - 8000
    depends_on:
      - https-portal
    volumes:
      - ./:/var/www/html
      - node_modules_volume:/var/www/html/node_modules
      - ./_docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build:
      context: ./_docker-configs/php-fpm
    depends_on:
      - pg
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - node_modules_volume:/var/www/html/node_modules
      - laravel-log:/var/www/html/storage/logs
  pg:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - PGUSER=${PG_USER}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-store:/var/lib/postgresql/data
  mackerel-agent:
    image: mackerel/mackerel-agent
    hostname: laravel-monitor-${APP_ENV}
    environment:
      - apikey=${MACKEREL_APIKEY}
      - enable_docker_plugin=true
      - include=/etc/mackerel-agent/conf.d/*.conf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/mackerel-agent/:/var/lib/mackerel-agent/
      - ./mackerel_conf:/etc/mackerel-agent/conf.d
      - laravel-log:/laravel_log
    depends_on:
      - web
  new-relic-agent:
    image: newrelic/infrastructure:latest
    container_name: newrelic-infra-${APP_ENV}
    hostname: newrelic-infra-${APP_ENV}
    network_mode: host
    cap_add:
      - SYS_PTRACE
    privileged: true
    pid: host
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NRIA_LICENSE_KEY=${NRIA_LICENSE_KEY}

volumes:
  db-store:
  https-portal-data:
  node_modules_volume:
  laravel-log:
