version: "3"
services:
  nginx:
    image: nginx:1.17.8-alpine
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/cert-key:/etc/nginx/ssl
  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - pg
      - mailhog
    ports:
      - 9000:9000
      - 8001:8001
      - 3000:3000
    environment:
      - HOST=0.0.0.0
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
      # - ../_docker-configs/xdebug/php.ini:/usr/local/etc/php/php.ini
      # - yarn-cache:/usr/local/share/.cache/yarn/v6
      # - exclude:/var/www/html/node_modules
  pg:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: "pg-pe-12"
  pggui:
    container_name: pgweb
    image: sosedoff/pgweb
    ports:
      - 8081:8081
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
