---
- name: git pull latest
  ansible.builtin.git:
    repo: git@github.com:ProjectEuropa/Europa.git
    dest: /home/project.europa/Europa
    version: master
    key_file: /home/project.europa/.ssh/github
    accept_hostkey: true
    force: true
  become: true

- name: set .env
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: project.europa
    group: docker
    mode: "{{ item.mode }}"
    backup: yes
  become: true
  with_items:
    - { src: "{{ playbook_dir + '/.env.' + group_names | join('') }}", dest: /home/project.europa/Europa/.env, mode: '0644' }

# ステージングのみのコード1回限りなので、通常はコメントアウトしておく。
# - name: Copy private key
#   ansible.builtin.copy:
#     src: "{{ playbook_dir + '/ssh_keys/id_rsa'}}"
#     dest: "/ssh.from.production/.ssh/id_rsa"
#     mode: "0600"
#   become: true

- name: deploy
  ansible.builtin.script:
    cmd: "{{ playbook_dir + '/deploy.sh' }}"
    chdir: /home/project.europa/Europa
  register: results
  become: true
