---
  - name: Ensure group "docker" exists with correct gid
    ansible.builtin.group:
      name: docker
      state: present
      gid: 1750
    become: true

  - name: Create user
    ansible.builtin.user:
      name: "{{ item.name }}"
      comment: "{{ item.comment|default(omit) }}"
      state: "{{ item.state }}"
      groups: "{{ item.group }}"
    with_items: "{{ os_users }}"
    become: true

  - name: Add /etc/sudoers
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      line: '{{ item.name }} ALL=(root) NOPASSWD:ALL'
      state: present
      validate: visudo -cf %s
    with_items: "{{ os_users }}"
    become: true

  - name: Deploy SSH Public Key
    ansible.posix.authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ lookup('file', 'pubkey/' +  item.enviroment + '/' + item.name) }}"
    with_items: "{{ os_users }}"
    become: true

  - name: Set sshd setting (PermitRootLogin yes -> no)
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
    become: true

  - name: Stop and Start ssh
    service:
      name: ssh
      state: restarted
    become: true
