name: E2E Test

on:
  schedule:
   - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Info
          SLACK_ICON_EMOJI: ':github:'
          SLACK_COLOR: info
          SLACK_TITLE: 定期通知
          SLACK_MESSAGE: 通知です。テストが始まります。

      - name: 'Run tests'
        uses: cypress-io/github-action@v2

      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channels: 'proj-クイズアプリ個別対応'
          message-text: 'Cypress tests failed! They have been placed in this thread, good luck.'
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Alert
          SLACK_ICON_EMOJI: ':github:'
          SLACK_COLOR: danger
          SLACK_TITLE: 失敗
          SLACK_MESSAGE: 失敗しました
