name: Laravel Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            vendor
            ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-*
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate --env=ci
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute Migration
        run: php artisan migrate --env=ci
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test --env=ci

  notify:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    needs: laravel-tests
    if: always()
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ needs.laravel-tests.result }}
          fields: repo,message,author,job,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
